"
Instance Variables:

	count	<Integer>
"
Class {
	#name : #MwCountMethodWrapperInstVars,
	#superclass : #MwMethodWrapperInstVars,
	#type : #variable,
	#instVars : [
		'count'
	],
	#category : #'MethodWrappers42-Examples'
}

{ #category : #accessing }
MwCountMethodWrapperInstVars >> count [
	"^ <Integer>"

	^ count
]

{ #category : #accessing }
MwCountMethodWrapperInstVars >> count: anInteger [
	^count := anInteger
]
