"
Instance Variables:

	time	<Integer>
"
Class {
	#name : #MwTimeMethodWrapperInstVars,
	#superclass : #MwCountMethodWrapperInstVars,
	#type : #variable,
	#instVars : [
		'time'
	],
	#category : #'MethodWrappers42-Examples'
}

{ #category : #accessing }
MwTimeMethodWrapperInstVars >> time [
	"^ <Integer>"

	^ time
]

{ #category : #accessing }
MwTimeMethodWrapperInstVars >> time: anInteger [
	^time := anInteger
]
